name: MLflow-CNN
channels:
  - defaults
dependencies:
  - pip
  - python=3.7.11
  - pip:
    - mlflow==1.23.1
    - numpy==1.21.5
    - pandas==1.3.5
    - pyyaml==6.0
    - tqdm==4.62.3
    - Pillow==9.0.1
    - tensorflow==2.8.0