name: MLflow-CNN
channels:
  - defaults
dependencies:
  - pip
  - python=3.7.11
  - pip:
    - alembic==1.7.6
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cloudpickle==2.0.0
    - colorama==0.4.4
    - databricks-cli==0.16.4
    - docker==5.0.3
    - entrypoints==0.4
    - flask==2.0.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - greenlet==1.1.2
    - idna==3.3
    - importlib-metadata==4.11.1
    - importlib-resources==5.4.0
    - itsdangerous==2.1.0
    - jinja2==3.0.3
    - mako==1.1.6
    - markupsafe==2.1.0
    - mlflow==1.23.1
    - numpy==1.21.5
    - packaging==21.3
    - pandas==1.3.5
    - prometheus-client==0.13.1
    - prometheus-flask-exporter==0.18.7
    - protobuf==3.19.4
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywin32==227
    - pyyaml==6.0
    - querystring-parser==1.2.4
    - requests==2.27.1
    - scipy==1.7.3
    - six==1.16.0
    - smmap==5.0.0
    - sqlalchemy==1.4.31
    - sqlparse==0.4.2
    - tabulate==0.8.9
    - tqdm==4.62.3
    - typing-extensions==4.1.1
    - urllib3==1.26.8
    - waitress==2.0.0
    - websocket-client==1.3.1
    - werkzeug==2.0.3
    - zipp==3.7.0
    - Pillow==9.0.1
    - tensorflow==2.8.0
